# Generated by Django 5.0.14 on 2026-08-05 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome da construtora')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='builders/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='builder', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'construtora',
                'verbose_name_plural': 'construtoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='nome da tabela')),
                ('description', models.TextField(verbose_name='descrição')),
                ('image', models.ImageField(upload_to='price_tables/', verbose_name='imagem')),
                ('drive_link', models.URLField(verbose_name='link do drive')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tables', to='portal.builder', verbose_name='construtora')),
            ],
            options={
                'verbose_name': 'tabela de preços',
                'verbose_name_plural': 'tabelas de preços',
                'ordering': ['-created_at'],
            },
        ),
    ]
