# Generated by Django 5.0.14 on 2026-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('kind', models.CharField(choices=[('PARTNER', 'Parceiro comercial'), ('MEMBER_AGENCY', 'Imobiliária associada')], default='PARTNER', max_length=20, verbose_name='tipo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='logo')),
                ('website_url', models.URLField(blank=True, verbose_name='site')),
                ('facebook_url', models.URLField(blank=True, verbose_name='facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='instagram')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'parceiro',
                'verbose_name_plural': 'parceiros',
                'ordering': ['order', 'name'],
            },
        ),
    ]
