# Generated by Django 5.0.14 on 2026-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('icon', models.CharField(help_text='Chave simbólica do ícone (ex: discount, crm, megaphone).', max_length=50, verbose_name='ícone')),
                ('description', models.TextField(verbose_name='descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'benefício',
                'verbose_name_plural': 'benefícios',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('group', models.CharField(choices=[('DIRETORIA', 'Diretoria'), ('TITULAR', 'Membro titular'), ('SUPLENTE', 'Membro suplente')], default='TITULAR', max_length=20, verbose_name='grupo')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='board/', verbose_name='foto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'integrante da diretoria',
                'verbose_name_plural': 'integrantes da diretoria',
                'ordering': ['group', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='pergunta')),
                ('answer', models.TextField(verbose_name='resposta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'pergunta frequente',
                'verbose_name_plural': 'perguntas frequentes',
                'ordering': ['order', 'id'],
            },
        ),
    ]
