# Generated by Django 5.0.14 on 2026-07-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='benefits/', verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.CharField(help_text='Chave simbólica do ícone de fallback (ex: discount, crm, megaphone).', max_length=50, verbose_name='ícone'),
        ),
    ]
