# Generated by Django 5.0.14 on 2026-07-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='revisado')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-created_at'],
            },
        ),
    ]
