# Generated by Django 5.0.14 on 2026-07-29 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='imagem de capa')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
